language: python
python: 
    - 2.7
    - 3.8

env:
    - OMV_ENGINE=NEURON
    - OMV_ENGINE=PyNEURON

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - omv list -V 
